In [113]:
import pandas as pd
import numpy as np

steam_2024_revenue = pd.read_csv(r'C:\Users\Cecilia\Downloads\ironhack\coursework\group work\group project week3\first_project_cfg\data\raw\Steam_2024_bestRevenue_1500.csv')

steam_2024_revenue.head()

name releaseDate  copiesSold  price    revenue  \
0                         WWE 2K24  07-03-2024      165301  99.99  8055097.0   
1            EARTH DEFENSE FORCE 6  25-07-2024      159806  59.99  7882151.0   
2        Sins of a Solar Empire II  15-08-2024      214192  49.99  7815247.0   
3                 Legend of Mortal  14-06-2024      440998  19.99  7756399.0   
4  Shin Megami Tensei V: Vengeance  13-06-2024      141306  59.99  7629252.0   

   avgPlaytime  reviewScore publisherClass                   publishers  \
0    42.365140           71            AAA                           2K   
1    29.651061           57          Indie                  D3PUBLISHER   
2    12.452593           88          Indie       Stardock Entertainment   
3    24.797817           76          Indie  Paras Games,Obb Studio Inc.   
4    34.258496           96             AA                         SEGA   

                                          developers  steamId  
0                                    Visual Concepts  2315690  
1                                            SANDLOT  2291060  
2  Ironclad Games Corporation,Stardock Entertainment  1575940  
3                                    Obb Studio Inc.  1859910  
4                                              ATLUS  1875830

In [114]:
# Convert the 'releaseDate' column to datetime with the correct format
steam_2024_revenue['releaseDate'] = pd.to_datetime(steam_2024_revenue['releaseDate'], format='%d-%m-%Y', errors='coerce')

# Check for any conversion errors
print(steam_2024_revenue['releaseDate'].isnull().sum(), "dates were not converted.")

# Display the updated DataFrame
steam_2024_revenue.head()

0 dates were not converted.


name releaseDate  copiesSold  price    revenue  \
0                         WWE 2K24  2024-03-07      165301  99.99  8055097.0   
1            EARTH DEFENSE FORCE 6  2024-07-25      159806  59.99  7882151.0   
2        Sins of a Solar Empire II  2024-08-15      214192  49.99  7815247.0   
3                 Legend of Mortal  2024-06-14      440998  19.99  7756399.0   
4  Shin Megami Tensei V: Vengeance  2024-06-13      141306  59.99  7629252.0   

   avgPlaytime  reviewScore publisherClass                   publishers  \
0    42.365140           71            AAA                           2K   
1    29.651061           57          Indie                  D3PUBLISHER   
2    12.452593           88          Indie       Stardock Entertainment   
3    24.797817           76          Indie  Paras Games,Obb Studio Inc.   
4    34.258496           96             AA                         SEGA   

                                          developers  steamId  
0                                    Visual Concepts  2315690  
1                                            SANDLOT  2291060  
2  Ironclad Games Corporation,Stardock Entertainment  1575940  
3                                    Obb Studio Inc.  1859910  
4                                              ATLUS  1875830

In [115]:
# Now, extract the year if the conversion was successful
if steam_2024_revenue['releaseDate'].notnull().all():
    steam_2024_revenue['releaseDate'] = steam_2024_revenue['releaseDate'].dt.year
else:
    print("Some dates could not be converted. Please check the data.")

# Display the updated DataFrame
steam_2024_revenue.head()

name  releaseDate  copiesSold  price    revenue  \
0                         WWE 2K24         2024      165301  99.99  8055097.0   
1            EARTH DEFENSE FORCE 6         2024      159806  59.99  7882151.0   
2        Sins of a Solar Empire II         2024      214192  49.99  7815247.0   
3                 Legend of Mortal         2024      440998  19.99  7756399.0   
4  Shin Megami Tensei V: Vengeance         2024      141306  59.99  7629252.0   

   avgPlaytime  reviewScore publisherClass                   publishers  \
0    42.365140           71            AAA                           2K   
1    29.651061           57          Indie                  D3PUBLISHER   
2    12.452593           88          Indie       Stardock Entertainment   
3    24.797817           76          Indie  Paras Games,Obb Studio Inc.   
4    34.258496           96             AA                         SEGA   

                                          developers  steamId  
0                                    Visual Concepts  2315690  
1                                            SANDLOT  2291060  
2  Ironclad Games Corporation,Stardock Entertainment  1575940  
3                                    Obb Studio Inc.  1859910  
4                                              ATLUS  1875830

In [116]:
steam_2024_revenue.reset_index(drop=True, inplace=True)
steam_2024_revenue.columns = [c.lower().strip() for c in steam_2024_revenue.columns.values.tolist()]
steam_2024_revenue.head()

name  releasedate  copiessold  price    revenue  \
0                         WWE 2K24         2024      165301  99.99  8055097.0   
1            EARTH DEFENSE FORCE 6         2024      159806  59.99  7882151.0   
2        Sins of a Solar Empire II         2024      214192  49.99  7815247.0   
3                 Legend of Mortal         2024      440998  19.99  7756399.0   
4  Shin Megami Tensei V: Vengeance         2024      141306  59.99  7629252.0   

   avgplaytime  reviewscore publisherclass                   publishers  \
0    42.365140           71            AAA                           2K   
1    29.651061           57          Indie                  D3PUBLISHER   
2    12.452593           88          Indie       Stardock Entertainment   
3    24.797817           76          Indie  Paras Games,Obb Studio Inc.   
4    34.258496           96             AA                         SEGA   

                                          developers  steamid  
0                                    Visual Concepts  2315690  
1                                            SANDLOT  2291060  
2  Ironclad Games Corporation,Stardock Entertainment  1575940  
3                                    Obb Studio Inc.  1859910  
4                                              ATLUS  1875830

In [117]:
unique_states = steam_2024_revenue['copiessold'].unique()
print(unique_states)

[165301 159806 214192 ... 501474 156339 544144]


In [118]:
unique_states = steam_2024_revenue['price'].unique()
print(unique_states)

[99.99 59.99 49.99 19.99 29.99 24.99 35.01  0.   12.99 17.99 14.99 32.99
  9.99 20.99 34.99 44.99  2.99 13.99 69.99 10.99  4.99  8.99 21.99 39.99
  7.99 15.99  5.99 11.99  6.99 16.99 32.   18.99  3.99 22.99  1.99 18.35
  9.25 17.9  12.49  6.5   5.49 54.99 20.   23.99  3.5   3.49  7.   27.99
 12.45 12.    2.    9.9  25.5  25.   26.99  9.79 17.76 33.32]


In [119]:
unique_states = steam_2024_revenue['revenue'].unique()
print(unique_states)

[8055097. 7882151. 7815247. ... 8641459. 8440898. 8125042.]


In [120]:
unique_states = steam_2024_revenue['avgplaytime'].unique()
print(unique_states)

[42.36514031 29.65106126 12.45259327 ... 11.89115179 14.733899
 30.16099468]


In [121]:
unique_states = steam_2024_revenue['reviewscore'].unique()
print(unique_states)

[ 71  57  88  76  96  79  81  78  95   0  91  42  68  82  99  62  90  98
  89  86  97  93  66  87  50  73  92  80  63  75  60  85  83  49  72  84
  53  55  94  70  77  67  58  61  11  51  69  74  39  54  43  33 100  64
  65  59  44  24  31  46  52  40  45  15  56  37  32  41  48  38  47  25]


In [122]:
unique_states = steam_2024_revenue['publisherclass'].unique()
print(unique_states)

['AAA' 'Indie' 'AA' 'Hobbyist']


In [123]:
unique_states = steam_2024_revenue['publishers'].unique()
print(unique_states)

['2K' 'D3PUBLISHER' 'Stardock Entertainment' ... 'Games Operators'
 'IRONMACE' 'Red Nexus Games Inc.,IndieArk']


In [124]:
unique_states = steam_2024_revenue['developers'].unique()
print(unique_states)

['Visual Concepts' 'SANDLOT'
 'Ironclad Games Corporation,Stardock Entertainment' ... 'Lavapotion'
 'CRAFTS ＆ MEISTER Co., Ltd' 'Red Nexus Games Inc.']


In [125]:
unique_states = steam_2024_revenue['steamid'].unique()
print(unique_states)

[2315690 2291060 1575940 ...  867210 1672500 1296610]


In [126]:
# Specify the path where you want to save the CSV
save_path = r'C:\Users\Cecilia\Downloads\ironhack\coursework\group work\group project week3\first_project_cfg\data\clean'

steam_2024_revenue.to_csv('steam_2024_revenue_clean')